### ISSUE TITLE
ReadAll can't be used for large files. Expect io.Reader instead of byte[] ?

### ISSUE THREAD

**Issue by xlucas** [bazil/fuse#126]
Firsteval, congrats for your library, that's some serious good work !

However, I found an issue with the HandleReadAller interface.

The expected byte slice represent the entire file content and thus the whole file is allocated in memory. This would lead to OOM on large files.

As a 'replacement', this is possible to simply implement the HandleReader interface. But this isn't a good solution neither when you have the entire file content at disposal and simply want to stream the data back as you don't have a way to tell if the entire file is being read (for instance a connected filesystem where your HTTP GET request returns an io.Reader for the body and simply want to stream the socket bytes back to the kernel).

This seems to be a good place to use an io.Reader or bufio.Reader interface. WDYF ?

**Comment by tv42** [comment]
Don't use `ReadAll` for large files. Some goes for all `*All` functions, including https://golang.org/pkg/io/ioutil/#ReadAll

The requests coming from from the kernel do not look like `io.Reader`, if anything they look a little like `io.ReaderAt`. Except with more metadata, hence `HandleReader`.

If your FUSE file contents come from a HTTP GET, you probably want something like https://github.com/DHowett/ranger and call that from your `Read` method.

If your FUSE file contents are not reproducible (are a "stream"), you'll need `fuse.OpenDirectIO`, and keep the `http.Response` alive in your Handle, make `Read` read from the `resp.Body`.

I'm not sure what there is to fix. Go `io` interfaces are simple because they carry no legacy; FUSE needs to match unix virtual filesystem behavior, which is much more complex. There may be utility functions and types written, but they'll work just as well residing outside of the `bazil.org/fuse` project, so I'd rather see the right APIs and behavior be worked out elsewhere first.

I'm not sure what there is to fix here.

**Comment by xlucas** [comment]
Thanks for the reply.

I ended up using `io.ReadFull(body, req.Size)` within the `Read` method and removed the `ReadAll` one. Shouldn't the ReadAller interface simply be removed ?

**Comment by tv42** [comment]
`ReadAller` is useful exactly in the scenarios `ioutil.ReadAll` is.

If you just use `io.ReadFull` like that, you're ignoring seeks. You might want to set `OpenNonSeekable`. https://godoc.org/bazil.org/fuse#OpenResponseFlags

It seems there is no bug here, just misunderstandings.
