### ISSUE TITLE
cannot set 'nonempty' mount option

### ISSUE THREAD

**Issue by kortschak** [bazil/fuse#153]
I am using a statically present mount point pinned by a file to make git keep it. This is part of a test suite.

Calling `fuse.Mount` on the mount point fails because of the pin file, complaining

```
2016/08/21 15:58:23 mount helper error: fusermount: mountpoint is not empty
2016/08/21 15:58:23 mount helper error: fusermount: if you are sure this is safe, use the 'nonempty' mount option
```

There does not appear to be any way in the fuse package API to pass this option through to `fusermount` via the `fuse.Mount` call.

Would you accept PR for a generic `Option(opt, val string)` (name space is constrained here) `MountOption` that sets `conf.options[opt] = val`?

**Comment by tv42** [comment]
Good news! We invented time travel and added the support before you asked! https://github.com/bazil/fuse/commit/1453c89b32d9d93ba1dd491c60a24438c381602a

No, I will not (without a *lot* of convincing) accept a generic "any mount option" support, because those mount options can change the protocol spoken with the kernel, and the library needs to be aware of that.

**Comment by kortschak** [comment]
I love when people do that (it doesn't happen often enough).
