### ISSUE TITLE
How to map NodeID for NodeRenamer?

### ISSUE THREAD

**Issue by anderspitman** [bazil/fuse#219]
Internally, I'm using a simple `map[string]fs.Node` cache (protected with a Mutex) to store my FUSE nodes. The string is just a Unix path. This has worked fine for reads/writes, however, I see that `RenameRequest` provides a `NodeID` for the new directory. So apparently I'll need a way to map node IDs to my paths. But where do I get the NodeIDs from? Is there some way to assign them myself for every new node? My best guess is that I need to manually handle `InitRequest` somehow, but I'm not currently using the low level API at all. Is it possible to mix it with the higher one?

**Comment by tv42** [comment]
Storing a complete path for files is tricky to get right, because that's not the unix design. It mostly works for read-only filesystems. It can be made to work, I know of FUSE filesystems that store all paths in one flat leveldb, but then you have to understand what you're doing and certain operations unix assumes to be cheap are no longer cheap...

The `bazil.org/fuse/fs` package maps `NodeID`s to `Node`s for you. You'll see the final argument to `Rename` is the new directory node, as a `Node` not `NodeID`. That's an interface implemented by whatever you returned from `Lookup`, `Mkdir` etc.

**Comment by anderspitman** [comment]
So I was able to make it work by doing a type assertion on `newDir` to my type, which has the path of the destination dir, which I can use to retrieve the backend node from the cache. Is this a reasonable approach? Feels a bit hacky.

**Comment by tv42** [comment]
Why does your Node contain a path, why do you need to retrieve the actual node based on that -- make Node be what you need it to be to write simpler code.

**Comment by anderspitman** [comment]
The backend filesystem is path-based, and there are update events that get sent to clients (of which there are different types besides just FUSE). These events are scoped by path. So I have to pay for the complexity of parsing the path and traversing down to update the specific node affected anyway. Keeping a separate data structure is a nice separation of concerns.
