### ISSUE TITLE
InvalidateNodeData hanging

### ISSUE THREAD

**Issue by anderspitman** [bazil/fuse#220]
I'm running into a deadlock situation, which seems to originate from `InvalidateNodeData` not returning. Are there certain scenarios I need to avoid in order to guarantee this won't happen? I tried commenting out the invalidation, and strangely even without invalidating the cache, the kernel seems to be returning the updated data as set from the backend.

**Comment by anderspitman** [comment]
I'm solving this for now by calling `InvalidateNodeData` in a goroutine, so at least the kernel eventually gets informed. But that feels pretty hacky.

**Comment by tv42** [comment]
`InvalidateNodeData` does some internal locking to map Node to NodeID and such, but after that it's a kernel upcall that takes however long it takes. That said, I've never seen it do anything anything else than return near-instantaneously. The kernel logic is mostly in `fuse_notify_inval_inode` and apart from a superblock-scoped semaphore to guard against simultaneous teardown, it doesn't have much in it that could sleep.

You'll need to provide more information.

**Comment by anderspitman** [comment]
Here's the scenario where I'm hitting the deadlock:

My backend filesystem is a network system (very similar to WebDAV or STFP) that allows subscribing to update events on any path. Any changes from one client trigger notifications to all clients. Currently, I don't have any logic to prevent updates also being sent to the client which initiated the mutation, which is where I'm hitting the problem.

Normal operation for a client requesting a change would go something like this (all of this happens in my implementation of `fs.Write`):

1. Lock the local cache
2. Get node from local cache
3. Unlock cache
4. Initiate the network request using info from the node
5. Receive the response and verify success
6. Lock cache
7. Update cache based on response
8. Unlock cache

The problem is that the update event is coming in between 4 and 5. Processing the update involves the same steps of locking and updating the local cache. The strange part is that it's blocking on `InvalidateNodeData` during the update, so step 6 of `Write` deadlocks. Could the kernel be doing some sort of locking until `Write` returns?

I can do more detailed debugging but I'm not sure what the next step is.

**Comment by tv42** [comment]
Oh you're trying to invalidate the node you are currently serving. That probably won't work.

I think you're blocked in the kernel with the codepath

```
fuse_notify_inval_inode
fuse_reverse_inval_inode
invalidate_inode_pages2_range
wait_on_page_writeback
```

Which waits for the write to complete, which you're not letting happen because you're waiting for the notify upcall, which won't complete because the page cache page is still in writeback, because...

As quick fix, you gotta filter your notifications. Even if you put the invalidation in a goroutine, that'd still be pretty silly behavior: shortly after the page is added to page cache, you're telling the kernel to discard it.

The better fix is to use a proper design. You basically cannot construct a (caching, multi-writer) cache-coherent distributed filesystem based on just invalidation notifications; you need leases. Anything the client loses the lease for needs to be discarded from kernel cache at that time. See e.g. NFSv4.

Unfortunately the scope of *this project* just simply cannot handle explaining filesystems, VFS, and such. I just don't have the time for that, and this project is not the authoritative place for such. Linux kernel, memory management, VFS, FUSE, and distributed systems are all concepts well beyond any feasible scope.

**Comment by anderspitman** [comment]
> As quick fix, you gotta filter your notifications

That's what I was thinking as well

> You basically cannot construct a (caching, multi-writer) cache-coherent distributed filesystem based on just invalidation notifications

Yeah I have no expectation of keeping the clients perfectly in sync. At this point it's expected behavior for data to get corrupted on concurrent writes. However, deadlock is undesirable. I'll probably add concurrent write functionality eventually, maybe starting with atomic writes based on file generations or hash, etc. Thanks for the lead on leases though; I'll definitely read up on that. Eventually I might implement leasing, locking, CRDT, etc.

> Unfortunately the scope of this project just simply cannot handle explaining filesystems, VFS, and such. I just don't have the time for that, and this project is not the authoritative place for such. Linux kernel, memory management, VFS, FUSE, and distributed systems are all concepts well beyond any feasible scope.

No worries! You've given me more than enough information of where to research from here. BTW I sent you an email inquiring about donating in appreciation for your time. Did you get it?
