### ISSUE TITLE
fstestutil: error message when unmounting

### ISSUE THREAD

**Issue by Merovius** [bazil/fuse#223]
When running tests using `fstestutil` (including running `go test` in `bazil.org/fuse` itself), I get the error message

```
2019/12/10 18:18:41 unmount error: exit status 1: fusermount: failed to unmount /tmp/fusetest865202780: Device or resource busy
```

printed on stderr. As far as I can tell, the temporary directory is properly unmounted and cleaned up. But the extra output makes tests quite noisy - especially when the tests pass, the error message is quite confusing.

**Comment by tv42** [comment]
Unfortunately we don't have a clear way of waiting until the mount is not busy, and we don't have a good way of categorizing fusermount errors either. At best that could be changed to a textual match, but then again we can't completely hide the error either because that's the only way to discover cleanup hanging because of leaky tests. It could be something like hide that specific error for the first N retries.

We're a victim of an ecosystem based on running obscure setuid helper binaries with poorly-thought-out interfaces :-(

https://github.com/bazil/fuse/blob/65cc252bf6691cb3c7014bcb2c8dc29de91e3a7e/fs/fstestutil/mounted.go#L38-L47

**Comment by Merovius** [comment]
Oh wow, I… only just realized why fusermount even exists (I always wondered). I always thought the kernel should be sufficiently fuse-aware that it's not needed…

A couple of ideas here:

1. Only log the error after finally giving up. Which would also help, because I would imagine getting 1K of these log lines if something *actually* goes wrong isn't super great either :)
2. Add an error return to Close and use that (after finally giving up, I guess?). This would probably be helpful anyway, because personally, I'd like the test to fail in that case, maybe? At least then someone would look at it, if it happens in CI :)
3. Add a `Logf func(format string, v ...interface{})` field to `fstestutil.Mount`, which is used for logging. You can even default it to `log.New(os.Stderr, "FUSE: ", 0)` or something if you want - but that way, I can set it to `t.Logf` and only see messages for failed tests.

Obviously, changing the API just for this might be overkill. And yeah, TBH I can't see a really *good* way to deal with it either… :-|

**Comment by tv42** [comment]
1. I'm worried about later error hiding detail from earlier error.
2. This is a test utility and I'd hate to push boilerplate into every test calling it.
3. I might just unconditionally use t.Logf for this. When this code was written, t.Logf was unconditionally buffered and almost useless for debugging FUSE, since most bugs showed up as hangs.

First pass might be just to silence that particular very common noise source on Linux.
