### ISSUE TITLE
Control-C to umount

### ISSUE THREAD

**Issue by wade-fs** [bazil/fuse#255]
I met that I must fuse umount the mountpoint after Ctrl-C the example programs.
Here is the solution for that, add the following after mountpoint := flag.Arg(0) (before mount)

    cc := make(chan os.Signal, 1)
    signal.Notify(cc, os.Interrupt)
    go func(){
        for range cc {
            fuse.Unmount(mountpoint)
        }
    }()

**Comment by tv42** [comment]
I don't think this belongs in the FUSE layer. If your application wants to react to control-C by unmounting, well, you've just demonstrated that's easy to do. Silently unmounting things is not always the right answer; for example, it can cause applications using the mountpoint to start creating files in the parent filesystem, instead of getting errors.
