### ISSUE TITLE
FS has no control over flags anymore

### ISSUE THREAD

**Issue by anacrolix** [bazil/fuse#97]
Now that FSIniter is gone, I cannot correct the passed flags to FS.Init. For example several of my filesystem implementations clobber the given flags per their requirements: one is single-threaded, another supports async reads, etc.

What is now the correct way to do this? Why did it change?

**Comment by tv42** [comment]
I encourage you to read the commit log. 928b86047a985283e77f22755718fbe4fd21c3b8 and 3ad48988b4b4b0a10aba0a4043dbd2a90e3e0e02 are relevant.

There's no such thing as single-threaded in InitFlags. I'm not sure what you're referring to there?

Async reads were already added 68fc4bea3531d56b141eb6ed41f380f5c9e55da0, http://godoc.org/bazil.org/fuse#AsyncRead

Let me know if something is still unclear after reading those.

**Comment by anacrolix** [comment]
Yes I follow that I must now set the flag during the Mount call. How do you recommend wrapping up the Mount so that init flags are set implicitly (as they can be particular to an FS).

The process to get a filesystem mounted is becoming quite convoluted. Can you comment on my use of your API in the function surrounding https://github.com/anacrolix/torrent/blob/master/cmd/torrentfs/main.go#L151 and https://github.com/anacrolix/torrent/blob/master/fs/torrentfs_test.go#L112.

It's unclear how to avoid duplicating passing InitAsyncRead during fs.Mount, and how exactly to unmount filesystems that are, or are not stuck (I call it "wedged", I'm sure you've encountered it). Additionally when or where to check conn.MountError is not clear.

**Comment by tv42** [comment]
Yes the Mount vs Serve API is a mess. This was largely caused by OSXFUSE mount behavior (timing of mount visibility and errors) being radically different from anything else. I'm still hoping to clean it up, but at least what's there now should be race-free.

The `<-conn.Ready; if err := conn.MountError; err != nil { ... }` pattern is the right one.

I'm not sure what you mean by "duplicating" there. Pass `fuse.AsyncRead()` to `fuse.Mount`. If you have multiple places calling Mount, then *that's* the duplication, not the arguments to it.

The way to unmount a FUSE filesystem on Linux is to run `fusermount -u MOUNTPOINT`. The way to force abort a FUSE connection is `echo 1 >/sys/fs/fuse/connections/NNN/abort` -- that also gets rid of mountpoints that are kept busy by e.g. open file descriptors. I don't know what you mean by "wedged".

I can't vouch for the defers you have in the code, there -- I didn't read it quite closely enough to see all the consequences. In general, you can't rely on a FUSE server to clean up after itself, because of `kill -9`. That would be undesirable anyway: Mounts should not just disappear, that'll just make you accidentally write to the underlying filesystem. Your `/home` partition does not unmount itself on hitting bad sectors, either.

There seems to be no bug reported here, as far as I can tell. Do keep asking questions, if I can help -- they're valuable as input for future documentation.
